spring.profiles.active=default

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/petstopdb

spring.datasource.username=postgres
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=update
